# Generated by Django 3.2.6 on 2022-10-14 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='contract',
            field=models.FileField(blank=True, null=True, upload_to='client_documents/%Y/%m/%d', verbose_name='Contrato'),
        ),
        migrations.AlterField(
            model_name='client',
            name='date',
            field=models.DateField(null=True, verbose_name='Data de recebimento dos documentos'),
        ),
        migrations.AlterField(
            model_name='client',
            name='proxy',
            field=models.FileField(blank=True, null=True, upload_to='client_documents/%Y/%m/%d', verbose_name='Procuração'),
        ),
    ]
