# Generated by Django 3.2.6 on 2022-08-14 17:07

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.FloatField(max_length=100, verbose_name='Orçamento'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client_cpf_cnpj',
            field=models.ForeignKey(on_delete=django.db.models.fields.NullBooleanField, to='main.client', verbose_name='CPF/CNPJ'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(default='', max_length=255, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='project',
            name='final_data',
            field=models.DateField(blank=True, null=True, verbose_name='Data de término'),
        ),
        migrations.AlterField(
            model_name='project',
            name='initial_data',
            field=models.DateField(verbose_name='Data de início'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=255, verbose_name='Nome do projeto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='representatives',
            field=models.CharField(default='', max_length=255, verbose_name='Representantes'),
        ),
        migrations.AlterField(
            model_name='project',
            name='responsible_person',
            field=models.CharField(default='', max_length=255, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Análise', 'Análise'), ('Aprovado', 'Aprovado'), ('Reprovado', 'Reprovado')], max_length=100, verbose_name='Status'),
        ),
    ]
