# Generated by Django 3.2.6 on 2022-10-14 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20221013_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de recebimento dos documentos'),
        ),
    ]
