# Generated by Django 3.2.6 on 2022-08-14 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220814_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='company_name',
            field=models.CharField(max_length=255, verbose_name='Nome da compania'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cpf_cnpj',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='CPF/CNPJ'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome completo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client_cpf_cnpj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.client', verbose_name='CPF/CNPJ'),
        ),
    ]
