# Generated by Django 3.2.6 on 2022-10-14 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_client_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='beneficiary_account',
            field=models.FileField(blank=True, null=True, upload_to='project_documents/%Y/%m/%d', verbose_name='Conta beneficiária'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client_documents',
            field=models.FileField(blank=True, null=True, upload_to='project_documents/%Y/%m/%d', verbose_name='CPF, RG ou CNH'),
        ),
        migrations.AlterField(
            model_name='project',
            name='generating_account',
            field=models.FileField(blank=True, null=True, upload_to='project_documents/%Y/%m/%d', verbose_name='Conta geradora'),
        ),
    ]
