# Generated by Django 3.2.6 on 2022-08-03 16:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=100)),
                ('company_name', models.CharField(max_length=255)),
                ('cpf_cnpj', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=255)),
                ('description', models.CharField(default='', max_length=255)),
                ('responsible_person', models.CharField(default='', max_length=255)),
                ('representatives', models.CharField(default='', max_length=255)),
                ('initial_data', models.DateField()),
                ('final_data', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Análise', 'Análise'), ('Aprovado', 'Aprovado'), ('Reprovado', 'Reprovado')], max_length=100)),
                ('budget', models.FloatField(max_length=100)),
                ('client_cpf_cnpj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client')),
            ],
        ),
    ]
